
ALTER TABLE pools ADD COLUMN IF NOT EXISTS status INTEGER NOT NULL DEFAULT 0;
UPDATE pools SET status = 3 WHERE canceled = TRUE;
UPDATE pools SET status = 4 WHERE finished = TRUE;

ALTER TABLE pools DROP COLUMN IF EXISTS canceled;
ALTER TABLE pools DROP COLUMN IF EXISTS finished;

ALTER TABLE requests ADD COLUMN IF NOT EXISTS status INTEGER NOT NULL DEFAULT 0;
UPDATE requests SET status = 3 WHERE delivered = TRUE;

ALTER TABLE requests DROP COLUMN IF EXISTS delivered;

UPDATE users SET location_id = 1 WHERE location_id IS NULL;

ALTER TABLE users ALTER COLUMN location_id SET NOT NULL;

DELETE FROM companies WHERE id NOT IN (SELECT company_id FROM users WHERE company_id IS NOT NULL);

ALTER TABLE companies ADD COLUMN IF NOT EXISTS owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE DEFAULT 1;
UPDATE companies c SET owner_id = (SELECT id FROM users WHERE company_id = c.id);

ALTER TABLE users DROP COLUMN IF EXISTS company_id;

ALTER TABLE companies ALTER COLUMN owner_id DROP DEFAULT;
ALTER TABLE users ALTER COLUMN location_id DROP DEFAULT;
ALTER TABLE categories ALTER COLUMN icon_name DROP DEFAULT;
ALTER TABLE products ALTER COLUMN category_id DROP DEFAULT;
ALTER TABLE pools ALTER COLUMN location_id DROP DEFAULT;
ALTER TABLE pools ALTER COLUMN status DROP DEFAULT;
ALTER TABLE requests ALTER COLUMN status DROP DEFAULT;

ALTER TABLE products ALTER COLUMN name SET NOT NULL;
ALTER TABLE products ALTER COLUMN company_id SET NOT NULL;
ALTER TABLE products ALTER COLUMN image_id SET NOT NULL;
ALTER TABLE products ALTER COLUMN category_id SET NOT NULL;

ALTER TABLE pools ALTER COLUMN product_id SET NOT NULL;
ALTER TABLE pools ALTER COLUMN location_id SET NOT NULL;

ALTER TABLE requests ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE requests ALTER COLUMN pool_id SET NOT NULL;

ALTER TABLE products ALTER COLUMN description TYPE VARCHAR(1024);

INSERT INTO migrations (id) VALUES (3);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(30) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    first_name VARCHAR(30) NOT NULL DEFAULT '',
    last_name VARCHAR(30) NOT NULL DEFAULT '',
    company_id INTEGER REFERENCES companies(id) ON DELETE CASCADE,
    location_id INTEGER DEFAULT 1 REFERENCES locations(id) ON DELETE SET DEFAULT
);