ALTER TABLE users ADD COLUMN IF NOT EXISTS validated BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS token VARCHAR(70) DEFAULT NULL;

ALTER TABLE reviews ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE requests RENAME COLUMN document_id TO down_payment_document_id;
ALTER TABLE requests ADD COLUMN IF NOT EXISTS final_payment_document_id INTEGER REFERENCES documents(id) ON DELETE CASCADE;

ALTER TABLE users ADD COLUMN IF NOT EXISTS admin BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE companies RENAME COLUMN active TO validated;

ALTER TABLE users ADD COLUMN IF NOT EXISTS block_level INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS blocked_until TIMESTAMP DEFAULT NULL;

ALTER TABLE companies DROP CONSTRAINT company_name_key;
ALTER TABLE companies DROP CONSTRAINT company_email_key;

INSERT INTO migrations (id) VALUES (5);