DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS companies CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS pools CASCADE;
DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;

DROP SEQUENCE IF EXISTS categories_id_seq;
DROP SEQUENCE IF EXISTS company_id_seq;
DROP SEQUENCE IF EXISTS documents_id_seq;
DROP SEQUENCE IF EXISTS locations_id_seq;
DROP SEQUENCE IF EXISTS pool_id_seq;
DROP SEQUENCE IF EXISTS product_id_seq;
DROP SEQUENCE IF EXISTS reports_id_seq;
DROP SEQUENCE IF EXISTS request_id_seq;
DROP SEQUENCE IF EXISTS reviews_id_seq;
DROP SEQUENCE IF EXISTS users_id_seq;

CREATE TABLE IF NOT EXISTS categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE,
    icon_name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS documents (
    id SERIAL PRIMARY KEY,
    bytes BLOB NOT NULL,
    filetype VARCHAR(100) NOT NULL,
    name VARCHAR(256) NOT NULL,
    is_public BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE IF NOT EXISTS locations (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    first_name VARCHAR(30) DEFAULT '' NOT NULL,
    last_name VARCHAR(30) DEFAULT '' NOT NULL,
    location_id INTEGER REFERENCES locations(id) ON DELETE SET NULL,
    validation_token VARCHAR(70) UNIQUE,
    password_token VARCHAR(70) UNIQUE,
    is_company BOOLEAN DEFAULT FALSE NOT NULL,
    validated BOOLEAN DEFAULT TRUE NOT NULL,
    admin BOOLEAN DEFAULT FALSE NOT NULL,
    block_level INTEGER DEFAULT 0 NOT NULL,
    blocked_until TIMESTAMP WITHOUT TIME ZONE,
    preferred_language VARCHAR(5) DEFAULT 'en' NOT NULL
);

CREATE TABLE IF NOT EXISTS companies (
    id SERIAL PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    address VARCHAR(100) NOT NULL,
    email VARCHAR(30) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    validated BOOLEAN DEFAULT FALSE NOT NULL,
    owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    document_id INTEGER REFERENCES documents(id) ON DELETE CASCADE,
    cbu VARCHAR(22) DEFAULT '' NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    document_id INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    UNIQUE (company_id, name)
);

CREATE TABLE IF NOT EXISTS pools (
    id SERIAL PRIMARY KEY,
    min_quantity INTEGER NOT NULL,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    location_id INTEGER NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    status VARCHAR(12) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    down_payment INTEGER DEFAULT 0 NOT NULL,
    price NUMERIC(10, 2) DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS reports (
    id SERIAL PRIMARY KEY,
    description VARCHAR(1024) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_reported BOOLEAN NOT NULL,
    company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests (
    id SERIAL PRIMARY KEY,
    quantity INTEGER NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    pool_id INTEGER NOT NULL REFERENCES pools(id) ON DELETE CASCADE,
    status VARCHAR(12) NOT NULL,
    down_payment_document_id INTEGER REFERENCES documents(id) ON DELETE CASCADE,
    final_payment_document_id INTEGER REFERENCES documents(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reviews (
    id SERIAL PRIMARY KEY,
    description VARCHAR(1024) NOT NULL,
    rating DOUBLE PRECISION NOT NULL,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    reviewer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL
);

CREATE SEQUENCE categories_id_seq START WITH 4 INCREMENT BY 1;
CREATE SEQUENCE company_id_seq START WITH 3 INCREMENT BY 1;
CREATE SEQUENCE documents_id_seq START WITH 7 INCREMENT BY 1;
CREATE SEQUENCE locations_id_seq START WITH 4 INCREMENT BY 1;
CREATE SEQUENCE pool_id_seq START WITH 4 INCREMENT BY 1;
CREATE SEQUENCE product_id_seq START WITH 4 INCREMENT BY 1;
CREATE SEQUENCE reports_id_seq START WITH 3 INCREMENT BY 1;
CREATE SEQUENCE request_id_seq START WITH 7 INCREMENT BY 1;
CREATE SEQUENCE reviews_id_seq START WITH 3 INCREMENT BY 1;
CREATE SEQUENCE users_id_seq START WITH 7 INCREMENT BY 1;
