export enum UserRole {
  ADMIN = 'ROLE_ADMIN',
  COMPANY_VERIFIED = 'ROLE_COMPANY_VERIFIED',
  COMPANY_UNVERIFIED = 'ROLE_COMPANY_UNVERIFIED',
  COMPANY_PENDING = 'ROLE_COMPANY_PENDING',
  CLIENT = 'ROLE_CLIENT',
}
