/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    BlockStatus: typeof import('./components/BlockStatus.vue')['default']
    BlockUserDialog: typeof import('./components/BlockUserDialog.vue')['default']
    CategoryList: typeof import('./components/CategoryList.vue')['default']
    CompanySelectorDialog: typeof import('./components/CompanySelectorDialog.vue')['default']
    MyPoolCard: typeof import('./components/MyPoolCard.vue')['default']
    NotificationContainer: typeof import('./components/NotificationContainer.vue')['default']
    PaginationLinks: typeof import('./components/PaginationLinks.vue')['default']
    PoolCard: typeof import('./components/PoolCard.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    ProductSelectorDialog: typeof import('./components/ProductSelectorDialog.vue')['default']
    ReportsDialog: typeof import('./components/ReportsDialog.vue')['default']
    RequestList: typeof import('./components/RequestList.vue')['default']
    ReviewForm: typeof import('./components/ReviewForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    ValidateCompanyDialog: typeof import('./components/ValidateCompanyDialog.vue')['default']
  }
}
