/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/companies/': RouteRecordInfo<'/companies/', '/companies', Record<never, never>, Record<never, never>>,
    '/companies/[id]': RouteRecordInfo<'/companies/[id]', '/companies/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/forgot-password': RouteRecordInfo<'/forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    '/internal-server-error': RouteRecordInfo<'/internal-server-error', '/internal-server-error', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/my-pools': RouteRecordInfo<'/my-pools', '/my-pools', Record<never, never>, Record<never, never>>,
    '/my-products': RouteRecordInfo<'/my-products', '/my-products', Record<never, never>, Record<never, never>>,
    '/my-requests': RouteRecordInfo<'/my-requests', '/my-requests', Record<never, never>, Record<never, never>>,
    '/not-found': RouteRecordInfo<'/not-found', '/not-found', Record<never, never>, Record<never, never>>,
    '/pools/': RouteRecordInfo<'/pools/', '/pools', Record<never, never>, Record<never, never>>,
    '/pools/[id]/': RouteRecordInfo<'/pools/[id]/', '/pools/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/pools/[id]/edit': RouteRecordInfo<'/pools/[id]/edit', '/pools/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/pools/create': RouteRecordInfo<'/pools/create', '/pools/create', Record<never, never>, Record<never, never>>,
    '/products/': RouteRecordInfo<'/products/', '/products', Record<never, never>, Record<never, never>>,
    '/products/[id]/': RouteRecordInfo<'/products/[id]/', '/products/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/products/[id]/edit': RouteRecordInfo<'/products/[id]/edit', '/products/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/products/create': RouteRecordInfo<'/products/create', '/products/create', Record<never, never>, Record<never, never>>,
    '/profile/': RouteRecordInfo<'/profile/', '/profile', Record<never, never>, Record<never, never>>,
    '/profile/change-password': RouteRecordInfo<'/profile/change-password', '/profile/change-password', Record<never, never>, Record<never, never>>,
    '/profile/companies/create': RouteRecordInfo<'/profile/companies/create', '/profile/companies/create', Record<never, never>, Record<never, never>>,
    '/profile/companies/edit': RouteRecordInfo<'/profile/companies/edit', '/profile/companies/edit', Record<never, never>, Record<never, never>>,
    '/profile/edit': RouteRecordInfo<'/profile/edit', '/profile/edit', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/reset-password': RouteRecordInfo<'/reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
    '/unauthorized': RouteRecordInfo<'/unauthorized', '/unauthorized', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/validate-account': RouteRecordInfo<'/validate-account', '/validate-account', Record<never, never>, Record<never, never>>,
  }
}
